easy_admin:
   site_name: '<img src="jci.png" width="100px" height="60px">'
   entities:
           #List the entity class name you want to manage
       - App\Entity\Action
       - App\Entity\Formation
      
   