vich_uploader:
    db_driver: orm

    mappings:

         Action:
             uri_prefix: '%uploads_path%'
             upload_destination: '%kernel.project_dir%/public/%uploads_path%'

         Formation : 
             uri_prefix: '%uploads_path%'
             upload_destination: '%kernel.project_dir%/public/%uploads_path%'

         